### ISSUE TITLE
The usersResendConfirmation method does not work

### ISSUE THREAD

**Issue by parijatsahai** [appcelerator/arrowdb-node-sdk#10]
In my app, the arrowDBApp.usersResendConfirmation method does NOT resend confirmation email. 

Looking at the ArrowDB node module, I think I might have found a bug. The Node SDK of ArrowDB contains a file called "users.js" in /lib/arrowdbObjects folder. This file has a bug in the line 46:

```
            requestResetPassword: {
                httpMethod: 'GET',
                restMethod: 'request_reset_password'
            },
            resendConfirmation: {
                httpMethod: 'GET',
                restMethod: 'resend_confirmation.json'
            },
```

As you can see above, the restMethod for resendConfirmation contains ".json" in the string which seems like a defect to me. Please resolve the defect asap.

**Comment by ewanharris** [comment]
This was fixed in #11 and released in version 1.0.9. So closing
